# Generated by Django 5.2.7 on 2025-10-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='foodCard_images/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('proteins', models.CharField(max_length=20)),
                ('fats', models.CharField(max_length=20)),
                ('carbohydrates', models.CharField(max_length=20)),
            ],
        ),
    ]
