# Generated by Django 5.2.7 on 2025-10-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meal_Planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcard',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
