# Generated by Django 5.2.7 on 2025-10-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meal_Planner', '0002_foodcard_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcard',
            name='category',
            field=models.CharField(choices=[('entries', 'Entries'), ('salads', 'Salads'), ('appetizers', 'Appetizers'), ('desserts', 'Desserts'), ('drinks', 'Drinks')], default='entries', max_length=50),
        ),
    ]
