# Generated by Django 5.2.7 on 2025-11-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meal_Planner', '0004_alter_foodcard_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='foodcard',
            name='carbohydrates',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foodcard',
            name='fats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foodcard',
            name='proteins',
            field=models.IntegerField(),
        ),
    ]
