# Generated by Django 5.2.7 on 2025-11-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meal_Planner', '0005_ingredient_alter_foodcard_carbohydrates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcard',
            name='description',
        ),
        migrations.AddField(
            model_name='foodcard',
            name='ingredients',
            field=models.ManyToManyField(to='Meal_Planner.ingredient'),
        ),
    ]
