# Generated by Django 5.2.7 on 2025-11-26 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meal_Planner', '0006_remove_foodcard_description_foodcard_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcard',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='foodcard',
            name='dairy_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodcard',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodcard',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodcard',
            name='nut_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodcard',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
