# Generated by Django 5.2.7 on 2025-11-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meal_Planner', '0007_remove_foodcard_ingredients_foodcard_dairy_free_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcard',
            old_name='vegan',
            new_name='vegetarian',
        ),
    ]
